rule twoBitInfo:
    input:
        "{sample}.2bit"
    output:
        "{sample}.chrom.sizes"
    log:
        "logs/{sample}.chrom.sizes.log"
    params:
        extra = "" # optional params string
    wrapper:
        "file:../../twoBitInfo"
