rule find_motifs:
    input:
        peak = "peaks_refs/{sample}.peaks",
        genome = "peaks_refs/gene.fasta"
    output:
        directory("motifs/{sample}/")
    params:
        extra = "-size 200"
    threads: 2
    log:
        "logs/findMotifs/{sample}.log"
    wrapper:
        "file:../../findMotifsGenome"