name: lefse cladogram
description: >
  LDA Effect Size (LEfSe) (Segata et. al 2010) is an algorithm for high-dimensional 
  biomarker discovery and explanation that identifies genomic features (genes, 
  pathways, or taxa) characterizing the differences between two or more biological 
  conditions.

authors:
  - dengxsh
input:
  - res file in tabular format
output:
  - cladogram file in pdf format
