rule meryldb:
    input:
        expand("{{sample}}.{run}.fastq", run=[1, 2]),
    output:
        directory("{sample}.meryl"),
    log:
        "logs/meryl/{sample}.log",
    params:
        extra = "",
        kmer = 31,
    threads: 4
    wrapper:
        "file:../../meryl"