name: hifiasm
description: |
  Hifiasm is a fast haplotype-resolved de novo assembler for PacBio HiFi reads. 
  It can assemble a human genome in several hours and assemble a ~30Gb California 
  redwood genome in a few days. Hifiasm emits partially phased assemblies of quality 
  competitive with the best assemblers. Given parental short reads or Hi-C data, it 
  produces arguably the best haplotype-resolved assemblies so far.
authors:
  - dengxsh
input:
  - fastq file
output:
  - GFA format assembly graphs files
