rule samtools_flagstat:
    input:
        bam = "mapped/{sample}.bam",
    output:
        "mapped/{sample}.bam.flagstat",
    log:
        "{sample}.log",
    params:
        extra = "",  # optional params string
    wrapper:
        "file:../../flagstat"
