name: juicer
description: |
  uicer is a platform for analyzing kilobase resolution Hi-C data. 
  In this distribution, we include the pipeline for generating Hi-C 
  maps from fastq raw data files and command line tools for feature 
  annotation on the Hi-C maps
url: https://github.com/aidenlab/juicer
authors:
  - dengxsh
input:
  - Sequences in FASTA format
  - chrom.sizes file
  - restriction enzyme site file
  - Hi-C reads in FASTQ format
  - juicer software path [Options]
output:
  - aligned reads in .hic format
notes: |
  * The `extra` param allows for additional program arguments.
