name: HicExplorer hicValidateLocations
description: |
  hicValidateLoops is a tool to compare the detect loops and TADs 
  from hicDetectLoops / hicFindTADs (or from any other software as 
  long as the data format is followed, see below) with known peak 
  protein locations to validate if the computed loops / TADs have 
  the expected anchor points
url: https://github.com/deeptools/HiCExplorer
authors:
  - dengxsh
input:
  - The loop file from hicDetectLoops, For TAD data use the boundaries.bed file and not the domains file!
  - The data file to validate the given locations. Can be narrowPeak, broadPeak (both in bed), or cool
output:
  - output_matched_locations and output_statistics.First file contains all loop locations with protein location matches, second file contains statistics about this matching.
params:
  extra: Any additional arguments to pass
notes: