rule annoPeak:
    input:
        peakfile = "test.narrowPeak",
        gtf = "a.gtf"
    output:
        expand('test.peakAnno.{ext}', ext=['pdf', 'txt'])
    params:
        sample = "test",
        output = "anno"
    wrapper:
        "file:../../../R/annoPeak"