name: HicExplorer hicCorrectMatrix
description: >
  This function provides 2 balancing methods which can be applied on a raw matrix.
  I. KR: It balances a matrix using a fast balancing algorithm introduced by Knight and Ruiz (2012).
  II. ICE: Iterative correction of a Hi-C matrix (see Imakaev et al. 2012 Nature Methods for details). 
  For this method to work correctly, bins with zero reads assigned to them should be removed as they 
  cannot be corrected. Also, bins with low number of reads should be removed, otherwise, during the 
  correction step, the counts associated with those bins will be amplified (usually, zero and low 
  coverage bins tend to contain repetitive regions). Bins with extremely high number of reads can also 
  be removed from the correction as they may represent copy number variations.
url: https://github.com/deeptools/HiCExplorer
authors:
  - dengxsh
input:
  - hic_matrix
output:
  - corrected_matrix or plot_file
params:
  extra: Any additional arguments to pass
notes:
