name: samtools index
description: Index bam file with samtools.
authors:
  - dengxsh
input:
  - bam file
output:
  - bam file index (.bai)
notes: |
  * The `extra` param allows for additional program arguments.
  * For more information see, http://www.htslib.org/doc/samtools-index.html
