rule samtools_merge:
    input:
        ["mapped/A.bam", "mapped/B.bam"],
    output:
        "merged.bam",
    log:
        "merged.log",
    params:
        extra = "",  # optional additional parameters as string
    threads: 2
    wrapper:
        "file:../../merge"
