name: pairtools_dedup
description: Find and remove PCR/optical duplicates
author:
  - dengxsh
input:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - input:
      type: file
      description: pair file
output:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"
  - pairs:
      type: file
      description: Duplicates removed pairs
      pattern: "*.{pairs.gz}"
  - stat:
      type: file
      description: stats of the pairs
      pattern: "*.{pairs.stat}"
