name: Pretext Map
description: Embeds bedgraph data into Pretext contact maps.
url: https://github.com/wtsi-hpag/PretextGraph
authors:
  - dengxsh
input:
  - BEDgraph file
output:
  - pretext contact map
notes: |
  * The `extra` param allows for additional arguments.
