name: purge_dups split_fa
description: Purge haplotigs and overlaps in an assembly based on read depth
url: https://github.com/dfguan/purge_dups
authors:
  - dengxsh
input:
  - stats file
output:
  - coverage cut-offs
notes: |
  * The `extra` param allows for additional program arguments.
