rule cooltools_eigs_trans:
    input:
        cooler = "CN.mm9.1000kb.mcool",  ## Multiresolution cooler file
        track = "mm9_1000000_gc.bed",
    output:
        vecs = "trans/CN_{resolution,[0-9]+}.trans.vecs.tsv",
        lam = "trans/CN_{resolution,[0-9]+}.trans.lam.tsv",
        bigwig = "trans/CN_{resolution,[0-9]+}.trans.bw",
    params:
        ## Add optional parameters
        track_col_name = "GC",
        extra = "",
    log:
        "logs/CN_{resolution}_trans_eigs.log",
    wrapper:
        "file:../../../cooltools/eigs_trans"
