channels:
  - conda-forge
  - bioconda
  - nodefaults
dependencies:
  - pysradb = 2.0.1
  - lxml = 4.6.3
  - pandas = 2.1.4
  - requests = 2.26.0
  - requests-ftp = 0.3.1
  - tqdm = 4.62.1
  - xmltodict = 0.12.0
