name: pysradb
description: |
  Query NGS metadata and data from NCBI Sequence Read Archive.
url: https://github.com/saketkc/pysradb
command:
  - metadata            Fetch metadata for SRA project (SRPnnnn)
  - download            Download SRA project (SRPnnnn)
  - search              Search SRA for matching text
  - gse-to-gsm          Get GSM for a GSE
  - gse-to-srp          Get SRP for a GSE
  - gsm-to-gse          Get GSE for a GSM
  - gsm-to-srp          Get SRP for a GSM
  - gsm-to-srr          Get SRR for a GSM
  - gsm-to-srs          Get SRS for a GSM
  - gsm-to-srx          Get SRX for a GSM
  - srp-to-gse          Get GSE for a SRP
  - srp-to-srr          Get SRR for a SRP
  - srp-to-srs          Get SRS for a SRP
  - srp-to-srx          Get SRX for a SRP
  - srr-to-gsm          Get GSM for a SRR
  - srr-to-srp          Get SRP for a SRR
  - srr-to-srs          Get SRS for a SRR
  - srr-to-srx          Get SRX for a SRR
  - srs-to-gsm          Get GSM for a SRS
  - srs-to-srx          Get SRX for a SRS
  - srx-to-srp          Get SRP for a SRX
  - srx-to-srr          Get SRR for a SRX
  - srx-to-srs          Get SRS for a SRX
input:
  accession number
output:
  - query results
notes: |
  * The `extra` param allows for additional program arguments.