rule jellyfish_count:
    input:
        "{prefix}.fasta",
    output:
        "{prefix}.jf",
    log:
        "{prefix}.jf.log",
    params:
        kmer=21,
        extra="--canonical",
    threads: 2
    resources:
        mem_gb = '1G',
    wrapper:
        "file:../../../jellyfish/count"
