rule bowtie2:
    input:
        reads = ["reads/{sample}.1.fastq", "reads/{sample}.2.fastq"],
        index = multiext(
            "index/genome",
            ".1.bt2",
            ".2.bt2",
            ".3.bt2",
            ".4.bt2",
            ".rev.1.bt2",
            ".rev.2.bt2",
        ),
    output:
        "mapped/{sample}.bam",
    log:
        "logs/bowtie2/{sample}.log",
    params:
        extra = "",  # optional parameters
        sort = "samtools"
    threads: 8  # Use at least two threads
    wrapper:
        "file:../../align"
