name: genomescope
description: >
  We have developed an analytical model and open-source software package 
  GenomeScope that can infer the global properties of a genome from 
  unassembled sequenced data. GenomeScope uses the k-mer count distribution, 
  e.g. from Jellyfish, and within seconds produces a report and several 
  informative plots describing the genome properties. We validate the 
  approach on simulated heterozygous genomes, as well as synthetic crosses 
  of related strains of microbial and eukaryotic genomes with known reference 
  genomes. GenomeScope was also applied to study the characteristics of several 
  novel species, including pineapple, pear, the regenerative flatworm 
  Macrostomum lignano, and the Asian sea bass.
authors:
  - dengxsh
input:
  - the k-mer count distribution, e.g. from KMC or Jellyfish
output:
  - several informative plots describing the genome properties
