
cluster-cancel: "scancel"
restart-times: "3"
jobscript: "slurm-jobscript.sh"
cluster: "slurm-submit.py"
# cluster-status: "slurm-status.py"
max-jobs-per-second: "10"
max-status-checks-per-second: "10"
local-cores: 10
latency-wait: "5"
use-conda: "True"
use-singularity: "False"
jobs: "10"
printshellcmds: "False"
rerun-incomplete: "True"

# Example resource configuration
default-resources:
  - runtime=10000
  - mem_mb=6000
  - disk_mb=1000000
# # set-threads: map rule names to threads
set-threads:
  - single_core_rule=1
  - multi_core_rule=10
# # set-resources: map rule names to resources in general
set-resources:
  - high_memory_rule:mem_mb=72000
  - long_running_rule:runtime=1200
