# --------------------- pipeline ---------------------
pipeline: "Assembly"
verbose: true

# -------------------- input data --------------------
data:
  ecoli: /cluster/facility/yzhang/WorkSpace/Reference/bowtie2/e.coli/e.coli

# --------------- programs parameters ----------------
parameters:
  hifiasm:
    extra: "-f 37 -l 1 -s 0.75 -O 1"
    threads: 32
    resourses: 160000
  bwa:
    extra: "-R '@RG\\tID:{sample}\\tSM:{sample}'"
    sort: "samtools"  # Can be 'none', 'samtools' or 'picard'.
    sort_order: "coordinate"  # Can be 'queryname' or 'coordinate'.
    sort_extra: ""

# ---------------- control parameters ----------------
control:
  assembly_mode: "solo"  # options: solo, HIC, trio