# -------------------- input data --------------------
data:
  # sample information
  sample_file: "../example/sample_list.txt"
  # genome files
  genome: hg19
  ref: /cluster/facility/yzhang/WorkSpace/Reference/genome/hg19.fa
  index: /cluster/facility/yzhang/WorkSpace/Reference/bowtie2/hg19/hg19
  ecoli: /cluster/facility/yzhang/WorkSpace/Reference/bowtie2/e.coli/e.coli
  gtf: /cluster/facility/yzhang/WorkSpace/Reference/annotation/hg19.refGene.gtf
  db: "../data"

# ------------------- output folder ------------------
workdir: null
# ------------------ wrapper folder ------------------
wrappers: "file:../wrappers"
scripts: "../scripts"
# --------------- programs parameters ----------------
parameters:
  fastp:
    extra: "-g -q 30 -u 50 -n 15 -l 36 -w 4"
  bowtie2:
    sort: samtools
    extra: "--end-to-end --very-sensitive --no-mixed --no-discordant --phred33 -I 10 -X 700"
  picard:
    MarkDuplicates: "--REMOVE_DUPLICATES true"
  trimmomatic:
    trimmer: ["LEADING:20", "TRAILING:20", "SLIDINGWINDOW:4:15", "MINLEN:25"]
    compression_level: "-9"
    mem: 1024
  alignmentSieve:
    mapq: 30
    flag: 2
    shift: "--ATACshift"
  
# ----------------- control argument -----------------
control:
  adapters: "Nextera"  # Truseq、Nextera
  spike_in: false