# ------------------------------ Pipeline ------------------------------ #
pipeline: "DNA-seq"  # Chip-seq、ATAC-seq
verbose: true

# reference data
data:
  dict: "/cluster/facility/yzhang/WorkSpace/GATK/hg19/Homo_sapiens_assembly19.dict"
# REGION_BED: "/cluster/facility/yzhang/WorkSpace/GATK/hg19/wgs_calling_regions.v1.interval_list"
  known_site:
    dbsnp: "/cluster/facility/yzhang/WorkSpace/GATK/hg19/dbsnp_138.b37.vcf.gz"
    indels: "/cluster/facility/yzhang/WorkSpace/GATK/hg19/Homo_sapiens_assembly19.known_indels.vcf"
    gold_standard: "/cluster/facility/yzhang/WorkSpace/GATK/hg19/Mills_and_1000G_gold_standard.indels.b37.vcf.gz"

parameters:
  vep:
    local:
      cache: ""
      plugins: ""
    online:
      species: homo_sapiens  # ensembl species name
      release: 98            # ensembl release
      build: GRCh37          # genome build, GRCh38
    plugins: LoFtool
  delly:
    exclude: "/cluster/facility/yzhang/WorkSpace/WGS/pipe/human.hg19.excl.tsv"
  gatk:
    vqsr:
      mills: "/cluster/facility/yzhang/WorkSpace/GATK/hg19/Mills_and_1000G_gold_standard.indels.b37.vcf.gz"
      mills_idx: "/cluster/facility/yzhang/WorkSpace/GATK/hg19/Mills_and_1000G_gold_standard.indels.b37.vcf.gz.tbi"
      omni: "/cluster/facility/yzhang/WorkSpace/GATK/hg19/1000G_omni2.5.b37.vcf.gz"
      omni_idx: "/cluster/facility/yzhang/WorkSpace/GATK/hg19/1000G_omni2.5.b37.vcf.gz.tbi"
      g1k: "/cluster/facility/yzhang/WorkSpace/GATK/hg19/1000G_phase1.snps.high_confidence.b37.vcf.gz"
      g1k_idx: "/cluster/facility/yzhang/WorkSpace/GATK/hg19/1000G_phase1.snps.high_confidence.b37.vcf.gz.tbi"
      dbsnp: "/cluster/facility/yzhang/WorkSpace/GATK/hg19/dbsnp_138.b37.vcf.gz"
      dbsnp_idx: "/cluster/facility/yzhang/WorkSpace/GATK/hg19/dbsnp_138.b37.vcf.gz"
      # General filtering parameters 
      QD: 2.0 
      QUAL: 30.0 
      ExcessHet:  54.69
    hard_filter:
      # SNPs filtering Parameters 
      snp_filter: "QD < 2.0 || FS > 60.0 || MQ < 40.0 || MQRankSum < -12.5 || ReadPosRankSum < -8.0"
      # INDELs filtering parameters 
      indel_filter: "QD < 2.0 || FS > 200.0 || ReadPosRankSum < -20.0"

control:
  adapters: "Nextera"      # Truseq(Illumina)、Nextera, use in cut&tag
  trimming: "fastp"        # choose: fastp(default)、cutadapt、trimmomatic and trim_galore
  mapping: "bwa"           # bowtie2、hisat2、star、minimap2
  dedup: "markduplicates"  # sambamba
  filter: "hard"           # or "vqsr"