rule cooler_dump:
    input:
        "mock.cool"
    output:
        "mock.bedpe"
    log:
        "logs/cooler/dump.log",
    params:
        extra = "-r 10:10,000,000-20,000,000 -r2 10:30,000,000-80,000,000 --header --join",
        table = "pixels",  # chroms|bins|pixels
    threads: 8
    wrapper:
        "file:../../../cooler/dump"