name: yahs
description: |
  YaHS is a scaffolding tool using Hi-C data. It relies on a new algothrim 
  for contig joining detection which considers the topological distribution 
  of Hi-C signals aiming to distingush real interaction signals from mapping 
  nosies. YaHS has been tested in a wide range of genome assemblies.
url: https://github.com/c-zhou/yahs
authors:
  - dengxsh
input:
  - contigs.fa
  - hic-to-contigs.bam
output:
  - directory
notes: |
  * The `extra` param allows for additional program arguments.
