name: HicExplorer 
description: Calculate GC content for a genome in bins
url: https://github.com/deeptools/HiCExplorer
authors:
  - dengxsh
input:
  - .bed file with bin coordinates
  - fasta file with the genome sequence
output:
  - >
    A tsv file with GC content in bins
params:
  extra: Any additional arguments to pass
notes:
