channels:
  - conda-forge
  - bioconda
  - nodefaults
dependencies:
  - r-base = 4.1.0
  - r-tidyverse  = 1.3.2
  - r-statmod = 1.5.0
  - r-jsonlite = 1.8.4
  - bioconductor-deseq2 = 1.34.0
  - bioconductor-edger = 3.36.0
  - bioconductor-limma = 3.50.0
  - bioconductor-geneplotter = 1.72.0