rule hisat2_index:
    input:
        fasta = "genome.fasta"
    output:
        directory("index")
    params:
        extra = "",
        prefix = "genome"
    log:
        "logs/hisat2_index.log"
    threads: 2
    wrapper:
        "file:../../../hisat2/index"
