rule salsa2:
    input:
        fas = "{sample}.fasta",
        fai = "{sample}.fasta.fai",
        bed = "{sample}.bed",
    output:
        directory("out")
    log:
        "logs/salsa2/{sample}.log",
    params:
        enzyme = "CTTAAG",  # optional
        extra = "--clean yes",  # optional
    resources:
        mem_mb=1024,
    wrapper:
        "file:../../salsa2"
