rule purge_dups_calcuts:
    input:
        "pbcstat.stat",
    output:
        "out/calcuts.cutoffs",
    log:
        "logs/calcuts.log",
    params:
        extra="-l 2 -m 4 -u 8",
    threads: 1
    wrapper:
        "file:../../../purge_dups/calcuts"
