rule seqtk_seq_fastq_to_fasta:
    input:
        "{prefix}.fastq",
    output:
        "{prefix}.fasta",
    log:
        "{prefix}.log",
    params:
        extra="-A",
    wrapper:
        "file:../../../seqtk/seq"
