rule star_index:
    input:
        fasta = "{genome}.fasta",
        gtf = GTF,
    output:
        directory("{genome}"),
    message:
        "Testing STAR index"
    threads: 1
    params:
        extra = "",
    log:
        "logs/star_index_{genome}.log",
    wrapper:
        "file:../../index"
