rule bwa_mem:
    input:
        reads = ["reads/{sample}.1.fastq", "reads/{sample}.2.fastq"],
        index = multiext("genome", ".amb", ".ann", ".bwt", ".pac", ".sa"),
    output:
        "mapped/{sample}.bam",
    log:
        "logs/bwa_mem/{sample}.log",
    params:
        extra = "-R '@RG\\tID:{sample}\\tSM:{sample}'",
        sort = "samtools",  # Can be 'none', 'samtools' or 'picard'.
        sort_order = "coordinate",  # Can be 'queryname' or 'coordinate'.
        sort_extra = "",  # Extra args for samtools/picard.
    threads: 2
    wrapper:
        "file:../../mem"
