name: jellyfish_merge
description: Merge jellyfish databases.
url: https://github.com/gmarcais/Jellyfish
authors:
  - dengxsh
input:
  - multiple jf kmer count files
output:
  - merged jf kmer count file
