rule mpilup:
    input:
        # single or list of bam files
        bam = "mapped/{sample}.bam",
        reference = "genome.fasta",
    output:
        "mpileup/{sample}.mpileup.gz",
    log:
        "logs/samtools/mpileup/{sample}.log",
    params:
        extra = "-d 10000",  # optional
    wrapper:
        "file:../../mpileup"
