genome = "test"

rule bwa_index:
    input:
        f"{genome}.fa",
    output:
        idx=multiext(f"{genome}", ".amb", ".ann", ".bwt", ".pac", ".sa"),
    log:
        f"logs/bwa_index/{genome}.log",
    params:
        algorithm="bwtsw",
    wrapper:
        "file:../../index"