rule bamtobed:
    input:
        "{sample}.bam",
    output:
        "{sample}.fastq.gz",
    log:
        "logs/bamtofastq/{sample}.log",
    params:
        extra="",  # optional parameters
    wrapper:
        "file:../../bamtofastq"
