name: HicExplorer chicDifferentialTest
description: |
  chicDifferentialTest tests if two locations under consideration of the reference 
  point have a different interaction count. For this either Fisher’s test or the 
  chi2 contingency test can be used. The file that is accepted for this test can 
  be created with chicAggregateStatistic. H0 assumes the interactions are not 
  different. Therefore the differential interaction counts are all where H0 was 
  rejected.
url: https://github.com/deeptools/HiCExplorer
authors:
  - dengxsh
input:
  - path to the aggregated files which should be used for the differential test.
output:
  - Output file for the differential results (Default “differentialResults.hdf5”).
params:
  extra: Any additional arguments to pass
notes: