rule bwa_mem2_index:
    input:
        fasta = "{genome}.fa",
    output:
        multiext("{genome}", ".0123", ".amb", ".ann", ".pac", ".bwt.2bit.64"),
    log:
        "logs/bwa-mem2_index/{genome}.log",
    wrapper:
        "file:../../../bwa-mem2/index"