rule seqtk_subsample_pe:
    input:
        R1="{sample}.1.fastq.gz",
        R2="{sample}.2.fastq.gz"
    output:
        R1="{sample}.1.subsampled.pe.fastq.gz",
        R2="{sample}.2.subsampled.pe.fastq.gz"
    params:
        n=3,
        seed=12345
    log:
        "logs/seqtk_subsample/{sample}.log"
    threads:
        1
    wrapper:
        "file:../../../seqtk/subsample"

rule seqtk_subsample_se:
    input:
        "{sample}.fastq.gz"
    output:
        "{sample}.subsampled.se.fastq.gz"
    params:
        n=3,
        seed=12345
    log:
        "logs/seqtk_subsample/{sample}.log"
    threads:
        1
    wrapper:
        "file:../../../seqtk/subsample"